version: '3.5'

services:

  search-service:
    image: response-juggler:0.1.0
    environment:
      PORT: 80
      NUM_CONNECTIONS: 100
      RESPONSE_MAIN_TEMPLATE: "queryweights.json"
      RESPONSE_PARTIAL_IDENT_QUERIES: "{{QUERIES}}"
      RESPONSE_PARTIAL_CONTENT_QUERIES: "doc_query_weights.json"
      RESPONSE_PARTIAL_SAMPLER_TYPE_QUERIES: "LIST"
      RESPONSE_PARTIAL_SAMPLER_MIN_NUM_QUERIES: 5
      RESPONSE_PARTIAL_SAMPLER_MAX_NUM_QUERIES: 20
      RESPONSE_FIELD_IDENT_QUERY: "{{QUERY}}"
      RESPONSE_FIELD_SAMPLER_TYPE_QUERY: "SINGLE"
      RESPONSE_FIELD_SAMPLER_ELEMENT_CAST_QUERY: "STRING"
      RESPONSE_FIELD_SAMPLER_SELECTION_QUERY: "milk,apple,wine,juice,spread,water,smoked,ham,cheese,chicken"
      RESPONSE_FIELD_IDENT_WEIGHT: "{{BOOL}}"
      RESPONSE_FIELD_SAMPLER_TYPE_WEIGHT: "SINGLE"
      RESPONSE_FIELD_SAMPLER_ELEMENT_CAST_WEIGHT: "FLOAT"
      RESPONSE_FIELD_SAMPLER_SELECTION_WEIGHT: "0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.98"
    ports:
      - "80:80"