version: '3.5'

services:

  search-service:
    image: response-juggler:0.1.0
    environment:
      PORT: 80
      RESPONSE_SEARCH_MIN_PRODUCTS: 5
      RESPONSE_SEARCH_MAX_PRODUCTS: 20
      RESPONSE_SEARCH_VAR_DOCS_KEY: "#DOCS"
      RESPONSE_SEARCH_VAR_PID_KEY: "#PID"
      RESPONSE_SEARCH_VAR_PID_SAMPLE: "p0,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19"
      RESPONSE_SEARCH_TEMPLATE: "searchresponse.json"
      RESPONSE_SEARCH_DOC_PARTIAL: "doc.json"
    ports:
      - "80:80"